backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: 'info'
    label: 'Información'
    folder: 'src/pages/info'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'info-post',
        }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Descripción', name: 'description', widget: 'text' }
      - { label: 'Imagen Portada', name: 'coverImage', widget: image }
      - { label: 'Contenido', name: 'content', widget: 'markdown' }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Landing Page'
        name: 'index'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page',
            }
          - { label: 'Titulo', name: 'title', widget: 'string' }
          - { label: 'Intro', name: 'intro', widget: 'markdown' }
          - {
              label: 'Cuando',
              name: 'when',
              widget: 'object',
              fields:
                [
                  { label: 'Nombre', name: 'name', widget: 'string' },
                  { label: 'Valor', name: 'value', widget: 'string' },
                ],
            }
          - {
              label: 'Lugar',
              name: 'where',
              widget: 'object',
              fields:
                [
                  { label: 'Nombre', name: 'name', widget: 'string' },
                  { label: 'Valor', name: 'value', widget: 'string' },
                ],
            }
          - { label: 'Confirm Button', name: 'confirmButton', widget: 'string' }
          - { label: 'Nota', name: 'note', widget: 'string' }
          - { label: 'Ceremonia Pre', name: 'ceremonyPre', widget: 'string' }
          - {
              label: 'Ceremonia Título',
              name: 'ceremonyTitle',
              widget: 'string',
            }
          - {
              label: 'Ceremonia Texto',
              name: 'ceremonyText',
              widget: 'markdown',
            }
          - {
              label: 'Celebración Pre',
              name: 'celebrationPre',
              widget: 'string',
            }
          - {
              label: 'Celebración Título',
              name: 'celebrationTitle',
              widget: 'string',
            }
          - {
              label: 'Celebración Texto',
              name: 'celebrationText',
              widget: 'markdown',
            }
          - { label: 'Info Title', name: 'infoTitle', widget: 'string' }
          - {
              label: 'Info Posts',
              name: 'infoPosts',
              widget: 'list',
              fields:
                [
                  { label: 'Link', name: 'link', widget: 'string' },
                  { label: 'Imagen', name: 'image', widget: 'image' },
                  { label: 'Title', name: 'title', widget: 'string' },
                  { label: 'Text', name: 'text', widget: 'string' },
                ],
            }
          - {
              label: 'Detalles',
              name: 'details',
              widget: 'list',
              fields:
                [
                  { label: 'Emoticono', name: 'emoticon', widget: 'string' },
                  { label: 'Title', name: 'title', widget: 'string' },
                  { label: 'Text', name: 'text', widget: 'string' },
                ],
            }
  - name: 'components'
    label: 'Components'
    files:
      - file: 'src/components/confirmation.md'
        label: 'Confirmation'
        name: 'confirmation'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'confirmation-component',
            }
          - { label: 'Titulo', name: 'title', widget: 'string' }
          - { label: 'Texto', name: 'text', widget: 'markdown' }
          - { label: 'Tab', name: 'tab', widget: 'string' }
          - { label: 'Input Nombre', name: 'nameInput', widget: 'string' }
          - { label: 'Selecciona Entrante', name: 'starter', widget: 'string' }
          - {
              label: 'Opciones Entrante',
              name: 'starterOptions',
              widget: 'list',
              fields:
                [
                  {
                    label: 'Nombre del entrante',
                    name: 'name',
                    widget: 'string',
                  },
                ],
            }
          - {
              label: 'Selecciona Principal',
              name: 'mainCourse',
              widget: 'string',
            }
          - {
              label: 'Opciones Entrante',
              name: 'mainCourseOptions',
              widget: 'list',
              fields:
                [
                  {
                    label: 'Nombre del principal',
                    name: 'name',
                    widget: 'string',
                  },
                ],
            }
          - {
              label: 'Checkbox Transporte',
              name: 'transport',
              widget: 'string',
            }
          - {
              label: 'Mensaje Confirmación aceptada',
              name: 'successMessage',
              widget: 'markdown',
            }
          - { label: 'Mensaje Error', name: 'errorMessage', widget: 'markdown' }
